### ISSUE TITLE
Could not start  Block Producer Node

### ISSUE THREAD

**Issue by inetconnector** [tdiesler/nessus-cardano#26]
when trying to run a block producer node with

docker run --detach \
    --name=prod \
    -p 3001:3001 \
    -e CARDANO_BLOCK_PRODUCER=true \
    -e CARDANO_TOPOLOGY="/var/cardano/config/mainnet-topology.json" \
    -e CARDANO_SHELLEY_KES_KEY="/var/cardano/config/keys/pool/kes.skey" \
    -e CARDANO_SHELLEY_VRF_KEY="/var/cardano/config/keys/pool/vrf.skey" \
    -e CARDANO_SHELLEY_OPERATIONAL_CERTIFICATE="/var/cardano/config/keys/pool/node.cert" \
    -v cardano-prod-config:/var/cardano/config  \
    -v /mnt/disks/data01:/opt/cardano/data \
    nessusio/cardano run

the container stops with logfile:

cardano-node: /var/cardano/config/keys/pool/vrf.skey: **getFileStatus: does not exist (No such file or directory)**

how can vrf.skey be copied to the container when the container is not running?

**Comment by inetconnector** [comment]
ok, this was missunderstanding of -v command of docker.

i first have to create directory /var/cardano/config manually on the host,
then copy mainnet-topology.json into it, also copy the files to

/var/cardano/config/keys/pool/kes.skey
/var/cardano/config/keys/pool/vrf.skey
/var/cardano/config/keys/pool/node.cert

**Comment by inetconnector** [comment]
cp kes.skey  /var/lib/docker/volumes/cardano-prod-config/_data/keys/pool/kes.skey 
cp node.cert  /var/lib/docker/volumes/cardano-prod-config/_data/keys/pool/node.cert
cp vrf.skey  /var/lib/docker/volumes/cardano-prod-config/_data/keys/pool/vrf.skey
cp mainnet-topology.json  /var/lib/docker/volumes/cardano-prod-config/_data/mainnet-topology.json

**Comment by tdiesler** [comment]
You'd likely want to use a volume for that i.e. don't copy these files to a running container
