### ISSUE TITLE
Migrate k8s node configuration to StatefulSets

### ISSUE THREAD

**Issue by tdiesler** [tdiesler/nessus-cardano#36]

**Comment by tdiesler** [comment]
I have an initial draft config for this [over here](https://github.com/tdiesler/nessus-cardano/blob/master/nix/docker/k8s/cardano-stafulset.yaml). On the Relay side, it uses this ...

```
        - name: CARDANO_TOPOLOGY
          value: '{
              "Producers": [
                {
                  "addr": "relays-new.cardano-mainnet.iohk.io",
                  "port": 3001,
                  "valency": 1
                },
                {
                  "addr": "bprod-headless.cardano.svc.cluster.local",
                  "port": 3001,
                  "valency": 1
                }
              ]
            }'
```

And on the Block Producer side, it uses this ...

```
        - name: CARDANO_TOPOLOGY
          value: '{
              "Producers": [
                {
                  "addr": "relay-headless.cardano.svc.cluster.local",
                  "port": 3001,
                  "valency": 1
                }
              ]
            }'
```

This would not scale, right? How can these topologies reference each other when we scale up?

**Comment by Marki4711** [comment]
We would need to have some sort of intelligence in the creation of the topology-file. I know some solutions that use the service-object of Kubernetes and query the ip-addresses of the pods that are registered to the. This results in a dynamic list a members which can be used as base to generate the topology-file. I never did it myself but this page describes something like it: https://medium.com/swlh/discovering-running-pods-by-using-dns-and-headless-services-in-kubernetes-7002a50747f4.
I am not sure, which service can do the fetch current ip-addresses of the service part and create an new topology file but the approach feels good to me.
We might implement the creation of the topology-file during container-startup but we need also a solution for changed number of members within the stake-pool. I don't have a good idea at the moment.

**Comment by bruceharrison1984** [comment]
If you got with a 'headless' k8s service, then you essentially are left with an SRV record that _does_ get updated dynamically as relays scale. The only thing that would need to be updated in that case is the Valency parameter of the relays on the BP topology. Which should be fairly easy by querying DNS and seeing how many records are attached to a given name. This processes should probably coincide with the already existing topology-updater so the two don't fight for access to the file at the same time.

**Comment by bruceharrison1984** [comment]
One thing  to note, not all cloud providers use the built in kubernetes DNS. DigitalOcean doesn't allow their k8s nodes to resolve k8s service names, which causes this approach to fail because the relay/BP can't locate one another. 

I hold that more as a failing of DigitalOcean using Cilium instead of the default k8s network implementaion, but be aware that networking seems to vary between cloud providers. GCP seems to use the 'vanilla' version.

**Comment by tdiesler** [comment]
Lovely, thanks. I think for now we could go with a solution that would not support scaling for the block producer, because that would require another set of configs, 500 ADA deposit, etc. We can put this into the config like this ...

```
  serviceName: bprod
  # A block producer cannot have more than 1 replicas
  replicas: 1
```

It is actually illegal, to use run multiple BP nodes with the same config. In Ethereum you get "slashed" heavily for doing so (even by accident). In Polkadot it is a "porcelain" offense, which means it is equivalent to a death sentence and you loose all your stake (at least that was what I read/understood when I checked last time) - really scary. Cardano does not have this sort of punishment and actually cannot take anything away from you because they don't control your stake - they can (and probably will) stop paying rewards to a pool that does this.

If I don't do anything with the BP topology, it would always use whatever K8S decides to be the target of `relay-headless.cardano.svc.cluster.local`, right? I assume that would always be the same relay node until that node disappears and K8S decides to route that name to a different node. I'd think that this is good enough for now.

For the relay, I think I'll try to access the K8S API from the entrypoint to figure out the CARDANO_PUBLIC_IP for that node, which then needs to be given to the topology updater. I assume that Alonzo will have a similar mechanism with which the node can tell the word where to find it. I already confirmed that I can access  the node from the outside as long as I know the external IP (correct firewall settings provided).

In that way, I think I can scale the relays to many. All of which connect to the same BP. The BP only connects to one of them. The relays find each other via topology updater or however Alonzo does it.

### Limitations

* The relay nodes are largely unaware of each other
* The BP only connects to one relay

I actually don't know why the BP needs to connect to friendly relay at all, when the relay already connects to the BP and pushes Tx for processing to it. That probability needs to be better understood, there is likely a good reason for it.

**Comment by bruceharrison1984** [comment]
I agree. The communication between relay/BP is very opaque and it makes decisions like this difficult. I do know that you can give the relay service URL to all relays, and then they are aware of each other.

The downside is each relay ends up with an open connection back to itself. I don't know what, if any, downside there is to this. 

It seems like the nodes themselves should check if the target IP matches the destination, and disregard the connection if it does. But that would be an upstream change, and I don't know Haskell 😆

**Comment by tdiesler** [comment]
> But that would be an upstream change

You could still file an issue that describes your concern. We could then track that.

**Comment by bruceharrison1984** [comment]
Done. https://github.com/input-output-hk/cardano-node/issues/2517
