### ISSUE TITLE
Block producer node prerequisites and stateful docker commands

### ISSUE THREAD

**Issue by Gizzbert** [tdiesler/nessus-cardano#40]
Hi,
I have been going through your gitbook and managed to spin up 2 relays, very nice and easy, ty!

2 things I found:

1- before running the producer nodes, all the steps in here: https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/getConfigFiles_AND_Connect.html need to be walked through, where your gitbook picks up at #9: "Start your nodes". I would suggest a reference to this guide on this page: https://tdiesler.gitbook.io/cardano/v/iohk/plain-docker/running-the-nodes

2- the running of stateful commands in the docker container as per https://tdiesler.gitbook.io/cardano/v/iohk/plain-docker/running-the-nodes under "Run stateful CLI commands" doesn;t appear to be working (for me)

thanks

**Comment by tdiesler** [comment]
1) should be done https://app.gitbook.com/@tdiesler/s/cardano/plain-docker/running-the-nodes#start-the-block-producer-node

2) You may want to be a bit more specific than that. Does the stateless approach work for you? Stateless, is just a matter of mapping (i.e. bind mounting) a local directory to where the container writes the output files to. There isn't anything more to it.

**Comment by tdiesler** [comment]
Please reopen if this is still an issue.
