### ISSUE TITLE
pool keys dir, raspberry data mount and custom peers 

### ISSUE THREAD

**Issue by Gizzbert** [tdiesler/nessus-cardano#43]
Hi
some more small findings which might help people going through the manual after me:

1. when following the gitbook here: https://tdiesler.gitbook.io/cardano/v/iohk/plain-docker/running-the-nodes, coming from the raspberry install section I was expecting to use the sda1 mount under "Run a relay node". What you do there initially is test if things work in the first place, but might be helpful to mention the -v node-data:/opt/cardano/data actually mounts a volume not on sda, but will on the final section of "Run a relay node". (In my case I left in the volume mapping in place and am only now copying the entire blockchain to /mnt/disks/data00, ie sudo docker cp tmp:/opt/cardano/data/. /mnt/disks/data00)

2. under https://tdiesler.gitbook.io/cardano/v/iohk/plain-docker/running-the-nodes#setup-the-config-volume-1 there are instructions to copy the keys to /var/cardano/config/keys, however in the section below that to start the block producer the path referenced is "/var/cardano/config/keys/pool/", they should be the same

3. The topology updater works fine for the relay, however the file mainnet-topology.json is overwritten with a new version after successful execution of the updater (as it should). This then overwrites the block producer entry in mainnet-topology.json and after a restart of the container the relay no longer connects back to the block producer. To remediate this we should add the custom peers parameter to the (relay only) docker run command:
	-e CARDANO_CUSTOM_PEERS="your-BP-IP:3001|relays-new.cardano-mainnet.iohk.io:3001:2" \

4. I found keeping the config in volumes was a tad cumbersome and have chosen to bind a directory on the host for easy manipulation of the config files ie "--mount type=bind,src=$HOME/cardano/config,target=/opt/cardano/config \". Especially if you want prometheus monitoring to work properly several tracers need to be enabled,  having easy access to the config makes manipulating the same a bit easier.

Happily running my pool 14ALL now due to your excellent writeup, ty!

**Comment by tdiesler** [comment]
@1 This is basic docker stuff, which we probably don't want to duplicate at this level. I guess folks are expected  to recognize and understand the difference between a volume and a bind mount. I added a link to the [docker volumes](https://docs.docker.com/storage/volumes) docs.

@2 Not necessarily. ~/cardano/keys can have subdirs. Still, I removed the 'pool' subdir in the config

@3 relay only is just that (i.e. no reference to the block producer). I added `-e CARDANO_CUSTOM_PEERS="bprod.ip.or.dns.name:3001"` to [Start the Relay Node](https://app.gitbook.com/@tdiesler/s/cardano/~/drafts/-MXjvw0kmdxuj-bEbQjd/plain-docker/running-the-nodes#start-the-relay-node)

@4 Sure, you may do that although its not recommended. In compose and k8s we support inline config

Thanks for the excellent feedback - keep it coming
