### ISSUE TITLE
Missing libselinux.so since 1.26.1

### ISSUE THREAD

**Issue by Beng89** [tdiesler/nessus-cardano#46]
Starting with version 1.26.1 and 1.26.2 of the cardano-tools image libselinux.so appears to be missing. This causes a large number of commands to fail resulting in errors like:

```sh
/bin/ls: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
mkdir: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
```

The 1.25.1 tag does not suffer from this issue.

**Comment by tdiesler** [comment]
Done
