### ISSUE TITLE
Topology updater might not working as expected

### ISSUE THREAD

**Issue by NITEMAN** [tdiesler/nessus-cardano#51]
Hi,

First of all thanks for your work.

Let me state that I'm quite new to Cardano so I might have some missconceptions.

I've managed to derive to a working testnet setup (based on `dev` tag), but despite topologyUpdate is running and I get multiple IN connections... OUT connections remains 2.

I've tried to see what's going on and my conclusions are:
* Topology file always get wiped on startup whenever `CARDANO_TOPOLOGY` env var contains a valid JSON, so if dealing with `CARDANO_UPDATE_TOPOLOGY`  topology file should be better mounted, ¿is that correct?. But if I mount the file I get `mv: cannot move '/var/cardano/config/testnet-topology.json.tmp' to '/var/cardano/config/testnet-topology.json': Device or resource busy` I'm not sure why. I'll try to mount containing folder.
* Despite `CARDANO_TOPOLOGY` (the file) gets updated, there is no way to tell cardano node to use refreshed file, I've tried even to SIGHUP node process inside container but resulted on a contanier crash. I guess there lack some glue that restarts the node on topology change ([since original uses wrappers + systemd to restart node process](https://cardano-community.github.io/guild-operators/#/Scripts/topologyupdater)) or some support on node side (I've found https://cardanoupdates.com/commits/133b35227fd86624e9fd85bf0302dcbaa8785bb5 which seems to adress it but can't found that on github to see the status). Also I'm not sure if this somewhat relates to #49

**Comment by NITEMAN** [comment]
Mounting a directory got rid of `mv: cannot move` error.

Given that topology file is correctly persisted (because node needs it beforehand starting), the only thing remaining will be restarting the node process (can be workaround-ed restarting the whole container since now the file is outside it).

Maybe the only changes needed should be in DOCS/READMES & in `/nix/docker/compose/cardano-nodes.yaml`

**Comment by tdiesler** [comment]
The node topology is ephemeral and implementation detail of the container. You could also say it is quite a hack that contradicts the main objective of autonomous/decentralized nodes (i.e. nodes that do not need to connect to central topology update service).

However, it is still needed for now so we cant take it out. With Alonzo however (i.e. soon), we will get proper p2p management. I'd rather not expose the topology update hack more than already necessary.

Thanks for the comment anyway, it might still be helpful to others.
