### ISSUE TITLE
Additional RTS flags for optimization of memory usage

### ISSUE THREAD

**Issue by jterrier84** [tdiesler/nessus-cardano#67]
**Background**
Following this guide: [https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032](https://forum.cardano.org/t/solving-the-cardano-node-huge-memory-usage-done/67032) it is possible to optimize the memory usage on nodes with limited HW resources, such as RaspPi's, by starting the cardano-node with additional flags.

**Actual situation**
The actual Nessus docker container does not provide the option of starting the node with the input of these additional parameters. 

**Change Request**
Allows to input flags for starting the cardano-node

**Comment by tdiesler** [comment]
There are two levels of this. First, we have Haskell runtime system flags. The other are container constraints at the Docker level. Both are supported. 

However, let's say, you limit memory usage to 6G at the Docker level, I would not know how the cardano-node binary would behave internally. It might just crash or start swapping- that would need to be found out.

Perhaps, you could have the conversation with the IOHK devs and report your findings here?

**Comment by jterrier84** [comment]
I’m running my other Relay and BP node since 3 weeks with these parameters and the difference in memory usage is remarkable compared to the Relay running with the Nessus image. In average the difference in memory usage between the Nessus node and the others is ranging between 20-30%.

**Comment by tdiesler** [comment]
Oh, good to know. I'll look into it. Thanks.

**Comment by jterrier84** [comment]
Thank you for having a look into it. Please note that I'm using a
slightly different parametrization than the one described in the official
Cardano forum. I notice a better memory consumption with the following
flags on my Raspberry Pi 4 8GB:

+RTS -N4 --disable-delayed-os-memory-return -qg -qb -c -RTS

The entire command to run the node looks like this: cardano-node +RTS -N4
--disable-delayed-os-memory-return -qg -qb -c -RTS run ...

Am Fr., 30. Juli 2021 um 17:18 Uhr schrieb Thomas Diesler <
***@***.***>:

**Comment by jterrier84** [comment]
Oh, I overlooked your question above. The other relay and my bp are running with the docker image provided by this project here: [speedwing-cardano-staking-pool-edu](https://github.com/speedwing/cardano-staking-pool-edu)

**Comment by tdiesler** [comment]
Could you please try `nessusio/cardano-node:1.28.0-dev`? I removed file logging by default and use ...

```
+RTS -N4 -A64m -c -RTS
```

as the default.

You're right, memory consumption drops considerably. I'm not at all sure about those RTS options and whether parallel gc should really be disabled - for now it is not, until I get convinced otherwise.

**Comment by jterrier84** [comment]
Cool! Thanks for the fast implementation. I will try it out immediately.

Am Mi., 4. Aug. 2021 um 12:25 Uhr schrieb Thomas Diesler <
***@***.***>:
