### ISSUE TITLE
Make MAX_PEERS editable

### ISSUE THREAD

**Issue by jterrier84** [tdiesler/nessus-cardano#72]
**Actual situation**
The environment variable MAX_PEERS can not be edited. It seems that it gets overwritten to a fixed value =15 in the topologyUpdate script. 

**New situation**
Make the MAX_PEERS variable configurable from outside the container.

**Comment by jterrier84** [comment]
After restarting the docker container, the MAX_PEERS variable was loaded into the topologyUpdater file.

**Comment by tdiesler** [comment]
I verified that `-e MAX_PEERS=6` works as expected and results in a topology update request with the corresponding parameter. However, I also observe this https://github.com/cardano-community/guild-operators/issues/1082

Leaving open for now.

**Comment by tdiesler** [comment]
This should be fixed now (on their end)
