### ISSUE TITLE
Support Guild Operators Scripts

### ISSUE THREAD

**Issue by thejoshsmith** [tdiesler/nessus-cardano#74]
Hi there,

Thanks for providing such an awesome repository. We've recently switched and are running it across multi-arch environments.

Just wondering if it would be possible to add support for the Guild Operators scripts? https://github.com/cardano-community/guild-operators

Cntools.sh is especially useful for stake pool management and operations!

**Comment by tdiesler** [comment]
That'd be out of scope unfortunately
