### ISSUE TITLE
run containers in the same machine

### ISSUE THREAD

**Issue by antoninu** [tdiesler/nessus-cardano#77]
Hi everyone.

I am wondering whether it is convenient to run both the relay and the producer on the same physical machine that I currently have. 

I am aware that according to the official documentation it is intended that they are separate hosts (one connected to the internet and one closed) in different machines, but couldn't this be achieved virtually by this setup by having a node per container?

I have seen that in another project that also uses containers the author reccomends to run them on separate machines for security reasons, does this project also recommend that or is this setup intended for running the containers in the same machine?

I am interested in running either the Docker Compose or the K8s approach.

Thank you.

**Comment by tdiesler** [comment]
Technically, you can even run the same node as both the bp and the relay. In a production env and especially when other people's money is at stake you'd want to have sufficient redundancy. Recommended are at least 2 relays for each bp - all in different locations.

Q like this are probably best be answered in the forum.

**Comment by antoninu** [comment]
Thank you for your response. Perfect, I can deploy two relay and one producer node, but is it save to have them hosted on the same machine? Or should I have one container per machine?

**Comment by tmvtmv** [comment]
@antoninu
The **most** secure option is to have separate machines, preferably geographically dispersed. If a relay is compromised or attacked, the other nodes are not influenced. To help the Cardano network - and yourself - using all nodes (both relay as bp) on different locations, on different machines is the best scenario.
