### ISSUE TITLE
Add support for leaderlog on arm64

### ISSUE THREAD

**Issue by jterrier84** [tdiesler/nessus-cardano#82]
When running the leaderlog schedule according instructions, the error message "WARNING: The requested image's platform (linux/arm64v8) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[Error] cncli not supported on this platform!" appears.

I pulled the nessusio/cardano-tool:1:30.1 on my Raspberry Pi 4 8GB with Ubuntu. I did the same on my Mac Mini M1 and the error message is the same.

**Comment by jterrier84** [comment]
This is an error message that appears when running the cardano-tools for leaderlog schedule according instruction

**Comment by tdiesler** [comment]
Related to https://github.com/AndrewWestberg/cncli/issues/83
Blocked by https://github.com/AndrewWestberg/cncli/issues/86
