### ISSUE TITLE
Haskell RTS options to reduce missed slots

### ISSUE THREAD

**Issue by tdiesler** [tdiesler/nessus-cardano#83]
The current default does not seem to work so well on a Pi4. 

```
CARDANO_RTS_OPTS="-N4 -A64m -c"
```

After a couple of days, I see 0.7% of all slots being missed

**Comment by jterrier84** [comment]
Following parameters improved the overall performance o my Pi's in the best way so far:

-N2 -I0.1 -Iw3600 -A64m -AL128M -n4m -F1.1 -H3500M -O3500M

No short dropouts anymore and less missed slots over an entire epoch.
